clio-lang/clio

.gitignore
index.js
internals/get/clio-get.js
internals/helpers/package.js
package-lock.json
package.json
tests/internals/clio-get.test.js

Now Clio is able to get packages from GitHub:
**Latest Version**
`$ clio get github.com/foo/bar`
**Specific Version/Tag**
`$ clio get github.com/foo/bar@0.2.1`

Implemented native Clio Package Manager

---

host/host.js

In the previous configuration, user were able to require as many CPUs as he wish. I've added a fallback system which handles the case that the user requires more CPUs than possibile (for example, requiring 10 CPUs on a 8 CPUs machine)

Fixed workers spawning

---

internals/import.js

Fix node.js imports

---

.github/workflows/push-checks.yml
.github/workflows/test.yml
evaluator/analyzer.js
internals/builtins.js
package-lock.json
package.json
syntax/parsing.js
tests/test.js

Added tests and prettier linting as a on-push workflow

GitHub actions migration

---

core/model.js
core/parser.js

I moved `model` into a separate file as we discussed.

Move model into model.js

---

cli/index.js
package.json
tests/utils/versionUtils.test.js
utils/versionUtils.js

#46 add supported node versions

---

cli/commands/ast.js
cli/commands/compile.js
cli/commands/highlight.js
cli/commands/new.js
cli/commands/run.js
cli/index.js
cli/lib/colors.js

Fixes #52 
This PR is intended to make our log messages more colorful.
I added colors for Error, Warning, Info and Success.

Turn log message more colorful

---

cli/commands/host.js
cli/commands/run.js
core/internals/array.js
core/internals/builtins.js
core/internals/flow.js
core/internals/functions.js
core/internals/io.js
core/internals/lazy.js

This allows unlimited recursions. I also moved IO out of `lazy.js`.

Fix lazy and refactor

---

tests/core/internals/array.test.js
tests/core/internals/builtins.test.js
tests/core/internals/lazy.test.js
tests/core/parser.test.js

Didn't improve much, but i had some spare time to add some tests :)

Improve test coverage

---

cli/commands/new.js
package-lock.json
package.json
tests/cli/compile/compile.test.js
tests/cli/highlight/highlight.test.js
tests/cli/init/new.test.js
tests/cli/misc/ast.test.js

Closes #64.
This PR introduces [Degit](https://github.com/Rich-Harris/degit), a simple tool for project scaffolding. Here I am using it to setup projects for node and browser.
I created two repositories to serve as templates:
https://github.com/clio-lang/template-node
https://github.com/clio-lang/template-browser
I also added to `clio new` a parameter `--target` that defaults to `node`. The project will be cloned according to this parameter. If anything but `browser` or `node` is passed, it raises an exception.

Improve new project structure

---

cli/commands/deps_commands/add.js
internals/deps/index.js
internals/get/clio-get.js

Make sure we fetch as an URL if we install using a github URL

---

cli/commands/build.js
cli/commands/new.js
cli/commands/tests/build.test.js
cli/lib/colors.js
package/packageConfig.js
package/tests/clio.test.toml
package/tests/packageConfig.test.js

Build dependencies

---

.github/workflows/push-checks.yml
cli/commands/deps.js
package/tests/dependencies.test.js

Move showDependencies to local scope

---

cli/commands/deps_commands/add.js
cli/commands/deps_commands/get.js
cli/commands/init.js
cli/commands/tests/build.test.js
package.json
package/config.js
package/dependencies.js
package/index.js
package/packageConfig.js
package/tests/clio.test.toml
package/tests/packageConfig.test.js
package/tests/url.test.js
package/utils/fetch.js
package/utils/ids.js
package/utils/parse.js
package/utils/parse.test.js
package/utils/url.js

- adds dependency namespaces
- installs user/repo (github)
Closes #104
Closes #105
Closes #106

Implement a dependency parser

---

core/clio.beef
core/generator.js
core/tests/generator.test.js

Add import as statement

---

cli/commands/build.js
cli/commands/tests/build.test.js

Copy non-clio files to build dir

---

cli/commands/new.js

Fix misleading success message

---

core/clio.beef
core/generator.js
core/lexer.js
core/tests/compiler.test.js
core/tests/generator.test.js
packages/internals/src/array.js
packages/internals/src/lazyMap.js
packages/internals/src/method.js
packages/internals/src/range.js
packages/internals/tests/array.test.js
packages/internals/tests/lazyMap.test.js
packages/internals/tests/method.test.js
packages/internals/tests/range.test.js

This PR adds multidimensional slices for range, arrays and lazy maps. 
- Add syntax rules for slicers
- Add generator rules for slicers
- Add the required runtime / methods for slicers
- Add tests for slicers

Add slices

---

packages/internals/src/method.js

Fixes #155 
Fixes a binding issue in our JS FFI
- Bind method to object in Method class

Fix method binding

---

packages/internals/src/array.js
packages/internals/tests/array.test.js

Add 'push' method for array (#159)

---

docs/reference/language/README.md
docs/reference/language/boolean.md
docs/reference/language/logical.md
package-lock.json
packages/core/clio.beef
packages/core/generator.js
packages/core/tests/compiler.test.js
packages/core/tests/generator.test.js

Adds boolean and logical operators to the language
- Add boolean to the grammar
- Add logical operators to the grammar
- Add the required runtime
- Add the required tests

Added boolean and logical operators

---

packages/core/generator.js
packages/core/tests/generator.test.js

Fixes #161
Fixes assignments
- Use `symbol.raw` instead of `symbol` in generator!

Fixes #161

---

package-lock.json
package.json
packages/internals/package.json
packages/internals/src/builtins.js
packages/internals/src/flow.js
packages/internals/src/functions.js
packages/internals/tests/builtins.test.js
packages/internals/tests/flow.test.js
packages/internals/tests/functions.test.js

Adds auto-curry to the language.
- Move JSFn to `functions.js`
- Add auto-curry to `JSFn` class
- Add auto-curry to `Fn` class

Add currying

---

package-lock.json
package.json
packages/core/clio.beef
packages/core/package-lock.json
packages/core/package.json

Use aliasing to simplify our syntax rules
- Aliases

Use aliasing in syntax file

---

packages/core/clio.beef
packages/core/compiler.js
packages/core/generator/rules.js
packages/core/generator/rules/return.js
packages/core/generator/rules/wrapped-expr.js
packages/core/lexer.js
packages/core/parser.js
packages/core/tests/language/clio/math.clio
packages/core/tests/language/clio/wrapped.clio
packages/core/tests/language/math.test.js
packages/core/tests/language/wrapped.test.js
packages/internals/src/flow.js

Fixes #151
Adds wrapped expressions
- Add syntax rules
- Add lexer rules
- Add generator rules

Adds wrapped expressions

---

docs/SUMMARY.md
docs/dev/README.md
docs/dev/general/coding-guidelines.md
packages/cli/commands/build.js
packages/cli/commands/tests/ast.test.js
packages/cli/commands/tests/highlight.test.js
packages/cli/lib/platforms.js
packages/core/generator/rules/anonymous-function.js
packages/core/generator/rules/dot-notation.js
packages/core/generator/rules/logical.js
packages/core/generator/rules/return.js
packages/core/generator/rules/set-var.js
packages/core/lexer.js
packages/core/parser.js
packages/core/tests/language/math.test.js
packages/core/tests/language/wrapped.test.js
packages/internals/src/arity.js
packages/internals/src/array.js
packages/internals/src/functions.js
packages/internals/src/lazyMap.js
packages/internals/src/range.js
packages/internals/tests/flow.test.js
packages/internals/tests/lazyMap.test.js

Fixes #134 
This cleans up some minor issues regarding pathjoins and equality checks
- Path Joins are used correctly
- Equality checks (`==`) have been replaced with deep equality checks (`===`)

Maintainance fixes

---

package.json

Fixes #XXX
Fix an issue with clio package installation.
- ...
- ...

Try and fix utils not found
